<?xml version="1.0"?>
<robot name="percy" xmlns:xacro="http://wwww.ros.org/wiki/xacro">
<xacro:include filename="$(find percy_model)/urdf/materials.xacro" />
<xacro:include filename="$(find percy_model)/urdf/percy_model_macros.xacro" />
<xacro:include filename="$(find percy_model)/urdf/percy_model.gazebo.xacro" />
<xacro:property name= "link_width" value= "0.02"/>
<xacro:property name="body_length" value="0.7"/>
<xacro:property name="body_width" value="0.5"/>
<xacro:property name="body_height" value="0.2"/>
<xacro:property name="work_height" value="0.3"/>
<xacro:property name="inner_strut_width" value="0.5"/>
<xacro:property name="leg_radius" value = "0.025"/>
<xacro:property name="theta" value="37"/>
<xacro:property name="leg_length" value="${(work_height+body_height)/(cos(radians(theta)))}"/>
<xacro:macro name="front_left_wheel_origin">
<origin xyz=" ${-1*((leg_length)*sin(radians(theta)))} ${body_width/2 + leg_radius} ${(body_height/2)-(leg_length*cos(radians(theta)))}" rpy="${radians(90)} 0.0 0.0"/>
</xacro:macro>
<xacro:property name="wheel_radius" value="0.1"/>
<xacro:property name="wheel_thickness" value="0.1"/>
<xacro:property name="wheel_mass" value="1"/>
<xacro:property name="camera_link_length" value="0.1"/>
<xacro:property name="camera_link_width" value="0.02"/>
<xacro:property name="camera_link_height" value="0.05"/>
<xacro:property name="wheel_dist" value="${body_width+leg_radius*4}"/>
<xacro:property name="density" value="2710"/>

<link name="origin">
    <origin xyz="0.0 0.0 0.0"/>
</link>

 <link name="link1">
  <pose> 0 0 3 0 0 0 </pose>
    <collision>
          <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>

        <geometry>
        <box size=" ${body_length} ${link_width} ${link_width}"/>   
        </geometry>
    </collision>
    <visual >
             <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
        <geometry>
            <box size="${body_length} ${link_width} ${link_width}"/>
        <material name="orange"/>
        </geometry>

    </visual>
    <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${body_length}" width="${link_width}" height="${link_width}"/>
    </inertial>
</link>

<joint name="joint1" type="fixed">
    <parent link="origin"/>
    <child link="link1"/>
     <origin rpy="0.0 0.0 0.0" xyz="0 ${body_width/2} ${body_height/2}"/>
    
</joint>

<link name="link2">
    
    <collision>
        <origin rpy="0.0 0.0 0" xyz="0 0 0"/>

        <geometry>
        <box size="${body_length} ${link_width} ${link_width}"/>   
        </geometry>
        </collision>
    <visual >
        <origin rpy="0.0 0.0 0" xyz="0 0 0"/>
        
        <geometry>
            <box size=" ${body_length} ${link_width} ${link_width}"/>
        </geometry>
    </visual>

        <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${body_length}" width="${link_width}" height="${link_width}"/>
    </inertial>
</link>

<joint name="joint2" type="fixed">
    <parent link="origin"/>
    <child link="link2"/>
     <origin rpy="0.0 0.0 0.0" xyz="0 ${-body_width/2} ${body_height/2}"/>
    
</joint>

<link name="link3">
    
     <collision>
        <origin rpy="0.0 0.0 0" xyz="0 0 0"/>

        <geometry>
        <box size="${link_width} ${body_width} ${link_width}"/>   
        </geometry>
        </collision>
    <visual >
        <origin rpy="0.0 0.0 0" xyz="0 0 0"/>
        
        <geometry>
            <box size="${link_width} ${body_width} ${link_width}"/>   
        </geometry>

    </visual>
    
    <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${body_width}" height="${link_width}"/>
    </inertial>
    </link>
<joint name="joint3" type="fixed">
    <parent link="origin"/>
    <child link="link3"/>
            <origin rpy="0.0 0.0 0" xyz="${body_length/2} 0 ${body_height/2}"/>

</joint>

<link name="link4">
    <collision>

        <geometry>
        <box size="${link_width} ${body_width} ${link_width}"/>   
        </geometry>
    </collision>

    <visual >
        
        <geometry>
            <box size="${link_width} ${body_width} ${link_width}"/>   
        </geometry>

    </visual>
        <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${body_width}" height="${link_width}"/>
    </inertial>

</link>
<joint name="joint4" type="fixed">
        <parent link="origin"/>

    <child link="link4"/>
        <origin rpy="0.0 0.0 0" xyz="${-body_length/2} 0 ${body_height/2}"/>
</joint>

<link name="link5">
  <pose> 0 0 3 0 0 0 </pose>
    <collision>
          <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>

        <geometry>
        <box size=" ${body_length} ${link_width} ${link_width}"/>   
        </geometry>
    </collision>
    <visual >
             <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
        <geometry>
            <box size="${body_length} ${link_width} ${link_width}"/>
        <material name="orange"/>
        </geometry>

    </visual>
    <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${body_length}" width="${link_width}" height="${link_width}"/>
    </inertial>
</link>
<joint name="joint5" type="fixed">
    <parent link="origin"/>
    <child link="link5"/>
     <origin rpy="0.0 0.0 0.0" xyz="0 ${body_width/2} ${-body_height/2}"/>
</joint>
<link name="link6">
    
    <collision>
        <origin rpy="0.0 0.0 0" xyz="0 0 0"/>

        <geometry>
        <box size="${body_length} ${link_width} ${link_width}"/>   
        </geometry>
        </collision>
    <visual >
        <origin rpy="0.0 0.0 0" xyz="0 0 0"/>
        
        <geometry>
            <box size=" ${body_length} ${link_width} ${link_width}"/>
        </geometry>
    </visual>

        <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${body_length}" width="${link_width}" height="${link_width}"/>
    </inertial>
</link>

<joint name="joint6" type="fixed">
    <parent link="origin"/>
    <child link="link6"/>
     <origin rpy="0.0 0.0 0.0" xyz="0 ${-body_width/2} ${-body_height/2}"/>
    
</joint>

<link name="link7">
    
     <collision>
        <origin rpy="0.0 0.0 0" xyz="0 0 0"/>

        <geometry>
        <box size="${link_width} ${body_width} ${link_width}"/>   
        </geometry>
        </collision>
    <visual >
        <origin rpy="0.0 0.0 0" xyz="0 0 0"/>
        
        <geometry>
            <box size="${link_width} ${body_width} ${link_width}"/>   
        </geometry>

    </visual>
    
    <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${body_width}" height="${link_width}"/>
    </inertial>
    </link>
<joint name="joint7" type="fixed">
    <parent link="origin"/>
    <child link="link7"/>
            <origin rpy="0.0 0.0 0" xyz="${body_length/2} 0 ${-body_height/2}"/>

</joint>

<link name="link8">
    <collision>

        <geometry>
        <box size="${link_width} ${body_width} ${link_width}"/>   
        </geometry>
    </collision>

    <visual >
        
        <geometry>
            <box size="${link_width} ${body_width} ${link_width}"/>   
        </geometry>

    </visual>
        <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${body_width}" height="${link_width}"/>
    </inertial>

</link>
<joint name="joint8" type="fixed">
        <parent link="origin"/>
    <child link="link8"/>
        <origin rpy="0.0 0.0 0" xyz="${-body_length/2} 0 ${-body_height/2}"/>
</joint>




  <link name="link9">
      
    <collision>

        <geometry>
            <box size="${link_width} ${link_width} ${body_height}"/>   
        </geometry>   
    </collision>
    <visual>
        <geometry>
            <box size="${link_width} ${link_width} ${body_height}"/>   
        </geometry>
    </visual>
        <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${link_width}" height="${body_height}"/>
    </inertial>
  </link>

<joint name="joint9" type="fixed">
        <parent link="origin"/>
    <child link="link9"/>
        <origin xyz="${body_length/2} ${body_width/2} ${0}"/>
</joint>

<link name="link10">
    
    <collision>

        <geometry>
        <box size="${link_width} ${link_width} ${body_height}"/>   
        </geometry>   
    </collision>
    <visual>
        <geometry>
            <box size="${link_width} ${link_width} ${body_height}"/>   
        </geometry>
    </visual>
            <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${link_width}" height="${body_height}"/>
    </inertial>
</link>
<joint name="joint10" type="fixed">
        <parent link="origin"/>
    <child link="link10"/>
        <origin xyz="${body_length/2} ${-body_width/2} ${0}"/>
</joint>

<link name="link11">
    
   
    <collision>

     <geometry>
      <box size="${link_width} ${link_width} ${body_height}"/>   
     </geometry>   
    </collision>
    <visual>
        <geometry>
            <box size="${link_width} ${link_width} ${body_height}"/>   
        </geometry>
    </visual>
                <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${link_width}" height="${body_height}"/>
    </inertial>
</link>
    <joint name="joint11" type="fixed">
        <parent link="origin"/>
    <child link="link11"/>
        <origin xyz="${-body_length/2} ${body_width/2} ${0}"/>
</joint>
    

<link name="link12">
    
    <collision>

     <geometry>
      <box size="${link_width} ${link_width} ${body_height}"/>   
     </geometry>   
    </collision>
    <visual>
        <geometry>
            <box size="${link_width} ${link_width} ${body_height}"/>   
        </geometry>
    </visual>
            <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${link_width}" height="${body_height}"/>
    </inertial>
</link>
    <joint name="joint12" type="fixed">
        <parent link="origin"/>
    <child link="link12"/>
        <origin xyz="${-body_length/2} ${-body_width/2} ${0}"/>
</joint> 

<!-- <link name="body">
    <collision>
        <geometry>
      <box size="${body_length} ${body_width} ${body_height}"/>   
     </geometry> 
    </collision>
    <visual>      
      <geometry>
      <box size="${body_length} ${body_width} ${body_height}"/>   
     </geometry> 
        
    </visual>

        <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${body_length}" width="${body_width}" height="${body_height}"/>
    </inertial>
</link>

<joint name="body_joint" type="fixed">
<origin xyz="0.0 0.0 0"/>
    <parent link="origin"/>
    <child link="body"/>
    
</joint> -->
 <link name="leg1">
     <collision>

        <geometry>
            <cylinder radius="${leg_radius}" length="${leg_length}"/>   
        </geometry>
    </collision>
    <visual>
        <geometry>
            <cylinder radius="${leg_radius}" length="${leg_length}"/>   
        </geometry>
    </visual>
                <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:cylinder_inertia l="${leg_length}" r="${leg_radius}" mass="${density*(pi*(leg_radius**2)*leg_length)}"/>
    </inertial>
</link>

    <joint name="joint_leg1" type="fixed">
        <parent link="origin"/>
    <child link="leg1"/>
        <origin xyz="${-1*((leg_length/2)*sin(radians(theta)))} ${body_width/2+leg_radius} ${(body_height/2)-((leg_length/2)*cos(radians(theta)))}" rpy="0.0 ${radians(theta)} 0.0"/>
</joint>

<link name="leg2">
    <collision>

        <geometry>
            <cylinder radius="${leg_radius}" length="${leg_length}"/>   
        </geometry>
    </collision>
    <visual>
        <geometry>
            <cylinder radius="${leg_radius}" length="${leg_length}"/>   
        </geometry>
    </visual>
                <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:cylinder_inertia l="${leg_length}" r="${leg_radius}" mass="${density*(pi*(leg_radius**2)*leg_length)}"/>
    </inertial>
</link>

    <joint name="joint_leg2" type="fixed">
        <parent link="origin"/>
    <child link="leg2"/>
        <origin xyz="${-1*((leg_length/2)*sin(radians(-theta)))} ${body_width/2+leg_radius} ${(body_height/2)-((leg_length/2)*cos(radians(-theta)))}" rpy="0.0 ${radians(-theta)} 0.0"/>
</joint>
<link name="leg3">
    <collision>

        <geometry>
            <cylinder radius="${leg_radius}" length="${leg_length}"/>   
        </geometry>
    </collision>
    <visual>
        <geometry>
            <cylinder radius="${leg_radius}" length="${leg_length}"/>   
        </geometry>
    </visual>
                <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:cylinder_inertia l="${leg_length}" r="${leg_radius}" mass="${density*(pi*(leg_radius**2)*leg_length)}"/>
    </inertial>
</link>

    <joint name="joint_leg3" type="fixed">
        <parent link="origin"/>
    <child link="leg3"/>
        <origin xyz="${-1*((leg_length/2)*sin(radians(theta)))} ${-body_width/2-leg_radius} ${(body_height/2)-((leg_length/2)*cos(radians(theta)))}" rpy="0.0 ${radians(theta)} 0.0"/>
</joint>

<link name="leg4">
    <collision>

        <geometry>
            <cylinder radius="${leg_radius}" length="${leg_length}"/>   
        </geometry>
    </collision>
    <visual>
        <geometry>
            <cylinder radius="${leg_radius}" length="${leg_length}"/>   
        </geometry>
    </visual>
                <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:cylinder_inertia l="${leg_length}" r="${leg_radius}" mass="${density*(pi*(leg_radius**2)*leg_length)}"/>
    </inertial>
</link>

    <joint name="joint_leg4" type="fixed">
        <parent link="origin"/>
    <child link="leg4"/>
        <origin xyz="${-1*((leg_length/2)*sin(radians(-theta)))} ${-body_width/2-leg_radius} ${(body_height/2)-((leg_length/2)*cos(radians(-theta)))}" rpy="0.0 ${radians(-theta)} 0.0"/>
</joint>
    
       

     <link name="link13">
        
    <collision>

        <geometry>
            <box size="${link_width} ${body_width} ${link_width}"/>
        </geometry>
    </collision>
    <visual>
        <geometry>
            <box size="${link_width} ${body_width} ${link_width}"/>
        </geometry>
    </visual>

    <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${body_width}" height="${link_width}"/>
    </inertial>
</link>

    <joint name="joint13" type="fixed">
        <parent link="origin"/>
    <child link="link13"/>
        <origin xyz="${inner_strut_width/2} 0.0 ${body_height/2}"/>
</joint> 


<link name="link14">
    
    <collision>

        <geometry>
            <box size="${link_width} ${body_width} ${link_width}"/>
        </geometry>
    </collision>
    <visual>
        <geometry>
            <box size="${link_width} ${body_width} ${link_width}"/>
        </geometry>
    </visual>
    <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${body_width}" height="${link_width}"/>
    </inertial>
</link>

    <joint name="joint14" type="fixed">
        <parent link="origin"/>
    <child link="link14"/>
        <origin xyz="${-inner_strut_width/2} 0.0 ${body_height/2}"/>
</joint> 




<link name="link15">
    <collision>
        <geometry>
            <box size="${link_width} ${body_width} ${link_width}"/>
        </geometry>
    </collision>
    <visual>
        <geometry>
            <box size="${link_width} ${body_width} ${link_width}"/>
        </geometry>
    </visual>
        <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${body_width}" height="${link_width}"/>
    </inertial>
</link>

    <joint name="joint15" type="fixed">
        <parent link="origin"/>
    <child link="link15"/>
        <origin xyz="${inner_strut_width/2} 0.0 ${-body_height/2}"/>
</joint> 


<link name="link16">
    <collision>
        <geometry>
            <box size="${link_width} ${body_width} ${link_width}"/>
        </geometry>
    </collision>
    <visual>
        <geometry>
            <box size="${link_width} ${body_width} ${link_width}"/>
        </geometry>
    </visual>

        <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${body_width}" height="${link_width}"/>
    </inertial>
</link>

    <joint name="joint16" type="fixed">
        <parent link="origin"/>
    <child link="link16"/>
        <origin xyz="${-inner_strut_width/2} 0.0 ${-body_height/2}"/>
</joint> 



<link name="link17">
    <collision>
        <geometry>
            <box size="${link_width} ${link_width} ${body_height}"/>
        </geometry>
    </collision>
    <visual>
        <geometry>
            <box size="${link_width} ${link_width} ${body_height}"/>
        </geometry>
    </visual>

        <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${link_width}" height="${body_height}"/>
    </inertial>
</link>

    <joint name="joint17" type="fixed">
        <parent link="origin"/>
    <child link="link17"/>
        <origin xyz="${inner_strut_width/2} ${body_width/2} 0"/>
</joint>  


<link name="link18">
    <collision>

        <geometry>
            <box size="${link_width} ${link_width} ${body_height}"/>
        </geometry>
    </collision>
    <visual>
        <geometry>
            <box size="${link_width} ${link_width} ${body_height}"/>
        </geometry>
    </visual>
        <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${link_width}" height="${body_height}"/>
    </inertial>
</link>

    <joint name="joint18" type="fixed">
        <parent link="origin"/>
    <child link="link18"/>
        <origin xyz="${inner_strut_width/2} ${-body_width/2} 0"/>
</joint>  


<link name="link19">
    <collision>

        <geometry>
            <box size="${link_width} ${link_width} ${body_height}"/>
        </geometry>
    </collision>
    <visual>
        <geometry>
            <box size="${link_width} ${link_width} ${body_height}"/>
        </geometry>
    </visual>

        <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${link_width}" height="${body_height}"/>
    </inertial>
</link>

    <joint name="joint19" type="fixed">
        <parent link="origin"/>
    <child link="link19"/>
        <origin xyz="${-inner_strut_width/2} ${body_width/2} 0"/>
</joint> 


<link name="link20">
    <collision>
    
        <geometry>
            <box size="${link_width} ${link_width} ${body_height}"/>
        </geometry>
    </collision>
    <visual>
        <geometry>
            <box size="${link_width} ${link_width} ${body_height}"/>
        </geometry>
    </visual>
        <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${link_width}" height="${body_height}"/>
    </inertial>
</link>

    <joint name="joint20" type="fixed">
        <parent link="origin"/>
    <child link="link20"/>
        <origin xyz="${-inner_strut_width/2} ${-body_width/2} 0"/>
</joint> 



<link name ="link21">
    <collision>

        <geometry>
            <box size="${link_width} ${body_width} ${link_width}"/>
        </geometry>
    </collision>
    <visual>
        <geometry>
            <box size="${link_width} ${body_width} ${link_width}"/>
        </geometry>
    </visual>
        <inertial>
     <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
     <xacro:link_inertia length="${link_width}" width="${body_width}" height="${link_width}"/>
    </inertial>
</link>

    <joint name="joint21" type="fixed">
        <parent link="origin"/>
    <child link="link21"/>
        <origin xyz="0 0 ${body_height/2}"/>
</joint> 



    

    

<link name="camera_link">
    <collision>
        <geometry>
            <box size="${camera_link_width} ${camera_link_length} ${camera_link_height}"/>
        </geometry>
    </collision>
    <visual>
    <geometry>
            <box size="${camera_link_width} ${camera_link_length} ${camera_link_height}"/>
        </geometry>
    </visual>
</link>

<joint name="camera_joint" type="fixed">
    <axis xyz="0.0 1.0 0.0"/>
    <origin xyz="${body_length/2} 0.0 ${-body_height/2 + (camera_link_height/2)+(link_width/2)}" rpy="0.0 0.75 0.0"/>
        <child link="camera_link"/>
        <parent link="origin"/>
</joint>
 <xacro:link_wheel name="link_rear_left_wheel" />
<xacro:joint_wheel name="joint_rear_left_wheel" child="link_rear_left_wheel" origin_xyz="${-1*((leg_length)*sin(radians(theta)))} ${body_width/2 +leg_radius*2 + (wheel_thickness/2)} ${(body_height/2)-(leg_length*cos(radians(theta)))}" />
 <xacro:link_wheel name="link_rear_right_wheel" />
<xacro:joint_wheel name="joint_rear_right_wheel" child="link_rear_right_wheel" origin_xyz="${-1*((leg_length)*sin(radians(theta)))} ${-(body_width/2 + leg_radius*2 + (wheel_thickness/2))} ${(body_height/2)-(leg_length*cos(radians(theta)))}" />
 <xacro:link_wheel name="link_front_left_wheel" />
<xacro:joint_wheel name="joint_front_left_wheel" child="link_front_left_wheel" origin_xyz="${((leg_length)*sin(radians(theta)))} ${body_width/2 +leg_radius*2 + (wheel_thickness/2)} ${(body_height/2)-(leg_length*cos(radians(theta)))}" />
 <xacro:link_wheel name="link_front_right_wheel" />
<xacro:joint_wheel name="joint_front_right_wheel" child="link_front_right_wheel" origin_xyz="${((leg_length)*sin(radians(theta)))} ${-(body_width/2 + leg_radius*2 + (wheel_thickness/2))} ${(body_height/2)-(leg_length*cos(radians(theta)))}" />
 

 <!-- <xacro:link_wheel name="link_rear_left_wheel" />
<xacro:joint_wheel name="joint_rear_left_wheel" child="link_rear_left_wheel" origin_xyz="-0.4 0.4 -0.5" />
 <xacro:link_wheel name="link_rear_right_wheel" />
<xacro:joint_wheel name="joint_rear_right_wheel" child="link_rear_right_wheel" origin_xyz="-0.4 -0.4 -0.5" />
 <xacro:link_wheel name="link_front_left_wheel" />
<xacro:joint_wheel name="joint_front_left_wheel" child="link_front_left_wheel" origin_xyz="0.4 0.4 -0.5" />
 <xacro:link_wheel name="link_front_right_wheel" />
<xacro:joint_wheel name="joint_front_right_wheel" child="link_front_right_wheel" origin_xyz="0.4 -0.4 -0.5" />
  -->

 <!-- <xacro:link_wheel name="link_rear_left_wheel" />
<xacro:joint_wheel name="joint_rear_left_wheel" child="link_rear_left_wheel" origin_xyz="-0.4 0.4 -0.4" />
 <xacro:link_wheel name="link_rear_right_wheel" />
<xacro:joint_wheel name="joint_rear_right_wheel" child="link_rear_right_wheel" origin_xyz="-0.4 -0.4 -0.4" />
 <xacro:link_wheel name="link_front_left_wheel" />
<xacro:joint_wheel name="joint_front_left_wheel" child="link_front_left_wheel" origin_xyz="0.4 0.4 -0.4" />
 <xacro:link_wheel name="link_front_right_wheel" />
<xacro:joint_wheel name="joint_front_right_wheel" child="link_front_right_wheel" origin_xyz="0.4 -0.4 -0.4" /> -->
 

</robot>
        <!-- <origin xyz=" ${-1*((leg_length)*sin(radians(theta)))} ${body_width/2 + leg_radius} ${(body_height/2)-(leg_length*cos(radians(theta)))}" rpy="${radians(90)} 0.0 0.0"/> -->
