// Generated by gencpp from file delta_coords/SendCoordsResult.msg
// DO NOT EDIT!


#ifndef DELTA_COORDS_MESSAGE_SENDCOORDSRESULT_H
#define DELTA_COORDS_MESSAGE_SENDCOORDSRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delta_coords
{
template <class ContainerAllocator>
struct SendCoordsResult_
{
  typedef SendCoordsResult_<ContainerAllocator> Type;

  SendCoordsResult_()
    : binary_result(0)  {
    }
  SendCoordsResult_(const ContainerAllocator& _alloc)
    : binary_result(0)  {
  (void)_alloc;
    }



   typedef uint32_t _binary_result_type;
  _binary_result_type binary_result;





  typedef boost::shared_ptr< ::delta_coords::SendCoordsResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delta_coords::SendCoordsResult_<ContainerAllocator> const> ConstPtr;

}; // struct SendCoordsResult_

typedef ::delta_coords::SendCoordsResult_<std::allocator<void> > SendCoordsResult;

typedef boost::shared_ptr< ::delta_coords::SendCoordsResult > SendCoordsResultPtr;
typedef boost::shared_ptr< ::delta_coords::SendCoordsResult const> SendCoordsResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delta_coords::SendCoordsResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delta_coords::SendCoordsResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delta_coords::SendCoordsResult_<ContainerAllocator1> & lhs, const ::delta_coords::SendCoordsResult_<ContainerAllocator2> & rhs)
{
  return lhs.binary_result == rhs.binary_result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delta_coords::SendCoordsResult_<ContainerAllocator1> & lhs, const ::delta_coords::SendCoordsResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delta_coords

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::delta_coords::SendCoordsResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delta_coords::SendCoordsResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delta_coords::SendCoordsResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delta_coords::SendCoordsResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_coords::SendCoordsResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_coords::SendCoordsResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delta_coords::SendCoordsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aad9d0ab8072ae8b469fcb3f4b59642c";
  }

  static const char* value(const ::delta_coords::SendCoordsResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaad9d0ab8072ae8bULL;
  static const uint64_t static_value2 = 0x469fcb3f4b59642cULL;
};

template<class ContainerAllocator>
struct DataType< ::delta_coords::SendCoordsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delta_coords/SendCoordsResult";
  }

  static const char* value(const ::delta_coords::SendCoordsResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delta_coords::SendCoordsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"uint32 binary_result\n"
;
  }

  static const char* value(const ::delta_coords::SendCoordsResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delta_coords::SendCoordsResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.binary_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendCoordsResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delta_coords::SendCoordsResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delta_coords::SendCoordsResult_<ContainerAllocator>& v)
  {
    s << indent << "binary_result: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.binary_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELTA_COORDS_MESSAGE_SENDCOORDSRESULT_H
