// Generated by gencpp from file delta_coords/SendCoordsFeedback.msg
// DO NOT EDIT!


#ifndef DELTA_COORDS_MESSAGE_SENDCOORDSFEEDBACK_H
#define DELTA_COORDS_MESSAGE_SENDCOORDSFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delta_coords
{
template <class ContainerAllocator>
struct SendCoordsFeedback_
{
  typedef SendCoordsFeedback_<ContainerAllocator> Type;

  SendCoordsFeedback_()
    : percent_complete(0.0)  {
    }
  SendCoordsFeedback_(const ContainerAllocator& _alloc)
    : percent_complete(0.0)  {
  (void)_alloc;
    }



   typedef float _percent_complete_type;
  _percent_complete_type percent_complete;





  typedef boost::shared_ptr< ::delta_coords::SendCoordsFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delta_coords::SendCoordsFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct SendCoordsFeedback_

typedef ::delta_coords::SendCoordsFeedback_<std::allocator<void> > SendCoordsFeedback;

typedef boost::shared_ptr< ::delta_coords::SendCoordsFeedback > SendCoordsFeedbackPtr;
typedef boost::shared_ptr< ::delta_coords::SendCoordsFeedback const> SendCoordsFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delta_coords::SendCoordsFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delta_coords::SendCoordsFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delta_coords::SendCoordsFeedback_<ContainerAllocator1> & lhs, const ::delta_coords::SendCoordsFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percent_complete == rhs.percent_complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delta_coords::SendCoordsFeedback_<ContainerAllocator1> & lhs, const ::delta_coords::SendCoordsFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delta_coords

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::delta_coords::SendCoordsFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delta_coords::SendCoordsFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delta_coords::SendCoordsFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delta_coords::SendCoordsFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_coords::SendCoordsFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_coords::SendCoordsFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delta_coords::SendCoordsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d342375c60a5a58d3bc32664070a1368";
  }

  static const char* value(const ::delta_coords::SendCoordsFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd342375c60a5a58dULL;
  static const uint64_t static_value2 = 0x3bc32664070a1368ULL;
};

template<class ContainerAllocator>
struct DataType< ::delta_coords::SendCoordsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delta_coords/SendCoordsFeedback";
  }

  static const char* value(const ::delta_coords::SendCoordsFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delta_coords::SendCoordsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"float32 percent_complete\n"
;
  }

  static const char* value(const ::delta_coords::SendCoordsFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delta_coords::SendCoordsFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendCoordsFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delta_coords::SendCoordsFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delta_coords::SendCoordsFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_complete: ";
    Printer<float>::stream(s, indent + "  ", v.percent_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELTA_COORDS_MESSAGE_SENDCOORDSFEEDBACK_H
