// Generated by gencpp from file delta_coords/SendCoordsGoal.msg
// DO NOT EDIT!


#ifndef DELTA_COORDS_MESSAGE_SENDCOORDSGOAL_H
#define DELTA_COORDS_MESSAGE_SENDCOORDSGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace delta_coords
{
template <class ContainerAllocator>
struct SendCoordsGoal_
{
  typedef SendCoordsGoal_<ContainerAllocator> Type;

  SendCoordsGoal_()
    : frontal_coord()  {
    }
  SendCoordsGoal_(const ContainerAllocator& _alloc)
    : frontal_coord(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _frontal_coord_type;
  _frontal_coord_type frontal_coord;





  typedef boost::shared_ptr< ::delta_coords::SendCoordsGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delta_coords::SendCoordsGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SendCoordsGoal_

typedef ::delta_coords::SendCoordsGoal_<std::allocator<void> > SendCoordsGoal;

typedef boost::shared_ptr< ::delta_coords::SendCoordsGoal > SendCoordsGoalPtr;
typedef boost::shared_ptr< ::delta_coords::SendCoordsGoal const> SendCoordsGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delta_coords::SendCoordsGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delta_coords::SendCoordsGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delta_coords::SendCoordsGoal_<ContainerAllocator1> & lhs, const ::delta_coords::SendCoordsGoal_<ContainerAllocator2> & rhs)
{
  return lhs.frontal_coord == rhs.frontal_coord;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delta_coords::SendCoordsGoal_<ContainerAllocator1> & lhs, const ::delta_coords::SendCoordsGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delta_coords

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::delta_coords::SendCoordsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delta_coords::SendCoordsGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delta_coords::SendCoordsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delta_coords::SendCoordsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_coords::SendCoordsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_coords::SendCoordsGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delta_coords::SendCoordsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe4b617d9fa0ac1f80b63d721c30ebe9";
  }

  static const char* value(const ::delta_coords::SendCoordsGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe4b617d9fa0ac1fULL;
  static const uint64_t static_value2 = 0x80b63d721c30ebe9ULL;
};

template<class ContainerAllocator>
struct DataType< ::delta_coords::SendCoordsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delta_coords/SendCoordsGoal";
  }

  static const char* value(const ::delta_coords::SendCoordsGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delta_coords::SendCoordsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"geometry_msgs/Point[] frontal_coord  \n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::delta_coords::SendCoordsGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delta_coords::SendCoordsGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frontal_coord);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SendCoordsGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delta_coords::SendCoordsGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delta_coords::SendCoordsGoal_<ContainerAllocator>& v)
  {
    s << indent << "frontal_coord[]" << std::endl;
    for (size_t i = 0; i < v.frontal_coord.size(); ++i)
    {
      s << indent << "  frontal_coord[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.frontal_coord[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELTA_COORDS_MESSAGE_SENDCOORDSGOAL_H
