// Generated by gencpp from file delta_coords/Test.msg
// DO NOT EDIT!


#ifndef DELTA_COORDS_MESSAGE_TEST_H
#define DELTA_COORDS_MESSAGE_TEST_H

#include <ros/service_traits.h>


#include <delta_coords/TestRequest.h>
#include <delta_coords/TestResponse.h>


namespace delta_coords
{

struct Test
{

typedef TestRequest Request;
typedef TestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Test
} // namespace delta_coords


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::delta_coords::Test > {
  static const char* value()
  {
    return "c63e85f503b805d84df783e71c6bb0d2";
  }

  static const char* value(const ::delta_coords::Test&) { return value(); }
};

template<>
struct DataType< ::delta_coords::Test > {
  static const char* value()
  {
    return "delta_coords/Test";
  }

  static const char* value(const ::delta_coords::Test&) { return value(); }
};


// service_traits::MD5Sum< ::delta_coords::TestRequest> should match
// service_traits::MD5Sum< ::delta_coords::Test >
template<>
struct MD5Sum< ::delta_coords::TestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::delta_coords::Test >::value();
  }
  static const char* value(const ::delta_coords::TestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::delta_coords::TestRequest> should match
// service_traits::DataType< ::delta_coords::Test >
template<>
struct DataType< ::delta_coords::TestRequest>
{
  static const char* value()
  {
    return DataType< ::delta_coords::Test >::value();
  }
  static const char* value(const ::delta_coords::TestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::delta_coords::TestResponse> should match
// service_traits::MD5Sum< ::delta_coords::Test >
template<>
struct MD5Sum< ::delta_coords::TestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::delta_coords::Test >::value();
  }
  static const char* value(const ::delta_coords::TestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::delta_coords::TestResponse> should match
// service_traits::DataType< ::delta_coords::Test >
template<>
struct DataType< ::delta_coords::TestResponse>
{
  static const char* value()
  {
    return DataType< ::delta_coords::Test >::value();
  }
  static const char* value(const ::delta_coords::TestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DELTA_COORDS_MESSAGE_TEST_H
