// Auto-generated. Do not edit!

// (in-package delta_coords.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SendCoordsResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.binary_result = null;
    }
    else {
      if (initObj.hasOwnProperty('binary_result')) {
        this.binary_result = initObj.binary_result
      }
      else {
        this.binary_result = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SendCoordsResult
    // Serialize message field [binary_result]
    bufferOffset = _serializer.uint32(obj.binary_result, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SendCoordsResult
    let len;
    let data = new SendCoordsResult(null);
    // Deserialize message field [binary_result]
    data.binary_result = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'delta_coords/SendCoordsResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'aad9d0ab8072ae8b469fcb3f4b59642c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    uint32 binary_result
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SendCoordsResult(null);
    if (msg.binary_result !== undefined) {
      resolved.binary_result = msg.binary_result;
    }
    else {
      resolved.binary_result = 0
    }

    return resolved;
    }
};

module.exports = SendCoordsResult;
