(cl:defpackage delta_coords-msg
  (:use )
  (:export
   "<SENDCOORDSACTION>"
   "SENDCOORDSACTION"
   "<SENDCOORDSACTIONFEEDBACK>"
   "SENDCOORDSACTIONFEEDBACK"
   "<SENDCOORDSACTIONGOAL>"
   "SENDCOORDSACTIONGOAL"
   "<SENDCOORDSACTIONRESULT>"
   "SENDCOORDSACTIONRESULT"
   "<SENDCOORDSFEEDBACK>"
   "SENDCOORDSFEEDBACK"
   "<SENDCOORDSGOAL>"
   "SENDCOORDSGOAL"
   "<SENDCOORDSRESULT>"
   "SENDCOORDSRESULT"
  ))

