; Auto-generated. Do not edit!


(cl:in-package delta_coords-msg)


;//! \htmlinclude SendCoordsResult.msg.html

(cl:defclass <SendCoordsResult> (roslisp-msg-protocol:ros-message)
  ((binary_result
    :reader binary_result
    :initarg :binary_result
    :type cl:integer
    :initform 0))
)

(cl:defclass SendCoordsResult (<SendCoordsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SendCoordsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SendCoordsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name delta_coords-msg:<SendCoordsResult> is deprecated: use delta_coords-msg:SendCoordsResult instead.")))

(cl:ensure-generic-function 'binary_result-val :lambda-list '(m))
(cl:defmethod binary_result-val ((m <SendCoordsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader delta_coords-msg:binary_result-val is deprecated.  Use delta_coords-msg:binary_result instead.")
  (binary_result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SendCoordsResult>) ostream)
  "Serializes a message object of type '<SendCoordsResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'binary_result)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'binary_result)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'binary_result)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'binary_result)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SendCoordsResult>) istream)
  "Deserializes a message object of type '<SendCoordsResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'binary_result)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'binary_result)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'binary_result)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'binary_result)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SendCoordsResult>)))
  "Returns string type for a message object of type '<SendCoordsResult>"
  "delta_coords/SendCoordsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SendCoordsResult)))
  "Returns string type for a message object of type 'SendCoordsResult"
  "delta_coords/SendCoordsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SendCoordsResult>)))
  "Returns md5sum for a message object of type '<SendCoordsResult>"
  "aad9d0ab8072ae8b469fcb3f4b59642c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SendCoordsResult)))
  "Returns md5sum for a message object of type 'SendCoordsResult"
  "aad9d0ab8072ae8b469fcb3f4b59642c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SendCoordsResult>)))
  "Returns full string definition for message of type '<SendCoordsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 binary_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SendCoordsResult)))
  "Returns full string definition for message of type 'SendCoordsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 binary_result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SendCoordsResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SendCoordsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SendCoordsResult
    (cl:cons ':binary_result (binary_result msg))
))
