; Auto-generated. Do not edit!


(cl:in-package delta_coords-msg)


;//! \htmlinclude SendCoordsGoal.msg.html

(cl:defclass <SendCoordsGoal> (roslisp-msg-protocol:ros-message)
  ((x
    :reader x
    :initarg :x
    :type cl:integer
    :initform 0)
   (y
    :reader y
    :initarg :y
    :type cl:integer
    :initform 0))
)

(cl:defclass SendCoordsGoal (<SendCoordsGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SendCoordsGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SendCoordsGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name delta_coords-msg:<SendCoordsGoal> is deprecated: use delta_coords-msg:SendCoordsGoal instead.")))

(cl:ensure-generic-function 'x-val :lambda-list '(m))
(cl:defmethod x-val ((m <SendCoordsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader delta_coords-msg:x-val is deprecated.  Use delta_coords-msg:x instead.")
  (x m))

(cl:ensure-generic-function 'y-val :lambda-list '(m))
(cl:defmethod y-val ((m <SendCoordsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader delta_coords-msg:y-val is deprecated.  Use delta_coords-msg:y instead.")
  (y m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SendCoordsGoal>) ostream)
  "Serializes a message object of type '<SendCoordsGoal>"
  (cl:let* ((signed (cl:slot-value msg 'x)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let* ((signed (cl:slot-value msg 'y)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SendCoordsGoal>) istream)
  "Deserializes a message object of type '<SendCoordsGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'x) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'y) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SendCoordsGoal>)))
  "Returns string type for a message object of type '<SendCoordsGoal>"
  "delta_coords/SendCoordsGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SendCoordsGoal)))
  "Returns string type for a message object of type 'SendCoordsGoal"
  "delta_coords/SendCoordsGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SendCoordsGoal>)))
  "Returns md5sum for a message object of type '<SendCoordsGoal>"
  "bd7b43fd41d4c47bf5c703cc7d016709")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SendCoordsGoal)))
  "Returns md5sum for a message object of type 'SendCoordsGoal"
  "bd7b43fd41d4c47bf5c703cc7d016709")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SendCoordsGoal>)))
  "Returns full string definition for message of type '<SendCoordsGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%int32 x ~%int32 y ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SendCoordsGoal)))
  "Returns full string definition for message of type 'SendCoordsGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%int32 x ~%int32 y ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SendCoordsGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SendCoordsGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SendCoordsGoal
    (cl:cons ':x (x msg))
    (cl:cons ':y (y msg))
))
