; Auto-generated. Do not edit!


(cl:in-package delta_coords-msg)


;//! \htmlinclude SendCoordsGoal.msg.html

(cl:defclass <SendCoordsGoal> (roslisp-msg-protocol:ros-message)
  ((frontal_coord
    :reader frontal_coord
    :initarg :frontal_coord
    :type (cl:vector geometry_msgs-msg:Point)
   :initform (cl:make-array 0 :element-type 'geometry_msgs-msg:Point :initial-element (cl:make-instance 'geometry_msgs-msg:Point))))
)

(cl:defclass SendCoordsGoal (<SendCoordsGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SendCoordsGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SendCoordsGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name delta_coords-msg:<SendCoordsGoal> is deprecated: use delta_coords-msg:SendCoordsGoal instead.")))

(cl:ensure-generic-function 'frontal_coord-val :lambda-list '(m))
(cl:defmethod frontal_coord-val ((m <SendCoordsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader delta_coords-msg:frontal_coord-val is deprecated.  Use delta_coords-msg:frontal_coord instead.")
  (frontal_coord m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SendCoordsGoal>) ostream)
  "Serializes a message object of type '<SendCoordsGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'frontal_coord))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'frontal_coord))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SendCoordsGoal>) istream)
  "Deserializes a message object of type '<SendCoordsGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'frontal_coord) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'frontal_coord)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'geometry_msgs-msg:Point))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SendCoordsGoal>)))
  "Returns string type for a message object of type '<SendCoordsGoal>"
  "delta_coords/SendCoordsGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SendCoordsGoal)))
  "Returns string type for a message object of type 'SendCoordsGoal"
  "delta_coords/SendCoordsGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SendCoordsGoal>)))
  "Returns md5sum for a message object of type '<SendCoordsGoal>"
  "fe4b617d9fa0ac1f80b63d721c30ebe9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SendCoordsGoal)))
  "Returns md5sum for a message object of type 'SendCoordsGoal"
  "fe4b617d9fa0ac1f80b63d721c30ebe9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SendCoordsGoal>)))
  "Returns full string definition for message of type '<SendCoordsGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/Point[] frontal_coord  ~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SendCoordsGoal)))
  "Returns full string definition for message of type 'SendCoordsGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/Point[] frontal_coord  ~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SendCoordsGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'frontal_coord) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SendCoordsGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SendCoordsGoal
    (cl:cons ':frontal_coord (frontal_coord msg))
))
